-- Sentinel AML initial schema.
-- Mirrors the entity model in com.sentinel.aml.entity: Customer -> Account -> Transaction,
-- and Customer -> Alert -> Case, with Alert's evidence transaction IDs held in a side table
-- (a plain string reference, not a foreign key, since evidence transactions may belong to
-- more than one alert and the relationship is informational, not referential).

CREATE TABLE customers (
    customer_id  VARCHAR(255) NOT NULL,
    full_name    VARCHAR(255),
    kyc_status   VARCHAR(255),
    risk_rating  VARCHAR(255),
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE accounts (
    account_id     VARCHAR(255) NOT NULL,
    customer_id    VARCHAR(255) NOT NULL,
    account_type   VARCHAR(255),
    currency_code  VARCHAR(255),
    CONSTRAINT accounts_pkey PRIMARY KEY (account_id),
    CONSTRAINT fk_accounts_customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE transactions (
    transaction_id              VARCHAR(255) NOT NULL,
    account_id                  VARCHAR(255) NOT NULL,
    amount                      NUMERIC(38, 2),
    currency_code               VARCHAR(255),
    counterparty_country_code   VARCHAR(255),
    channel                     VARCHAR(255),
    transaction_timestamp       TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id),
    CONSTRAINT fk_transactions_account FOREIGN KEY (account_id) REFERENCES accounts (account_id)
);

CREATE TABLE alerts (
    alert_id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id          VARCHAR(255) NOT NULL,
    triggered_rule_type  VARCHAR(255)
        CONSTRAINT alerts_triggered_rule_type_check
        CHECK (triggered_rule_type IN ('LARGE_TRANSACTION', 'STRUCTURING', 'HIGH_RISK_JURISDICTION')),
    risk_score           INTEGER,
    explanation          VARCHAR(2000),
    status               VARCHAR(255)
        CONSTRAINT alerts_status_check
        CHECK (status IN ('OPEN', 'DISPOSITIONED')),
    created_at           TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT alerts_pkey PRIMARY KEY (alert_id),
    CONSTRAINT fk_alerts_customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE alert_evidence_transactions (
    alert_id        BIGINT NOT NULL,
    transaction_id  VARCHAR(255),
    CONSTRAINT fk_alert_evidence_alert FOREIGN KEY (alert_id) REFERENCES alerts (alert_id)
);

CREATE TABLE cases (
    case_id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    alert_id             BIGINT NOT NULL,
    disposition_status   VARCHAR(255)
        CONSTRAINT cases_disposition_status_check
        CHECK (disposition_status IN ('CLEARED_FALSE_POSITIVE', 'ESCALATED_TO_FIU', 'CONFIRMED_SUSPICIOUS')),
    disposition_reason   VARCHAR(255),
    analyst_id           VARCHAR(255),
    dispositioned_at     TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT cases_pkey PRIMARY KEY (case_id),
    CONSTRAINT cases_alert_id_unique UNIQUE (alert_id),
    CONSTRAINT fk_cases_alert FOREIGN KEY (alert_id) REFERENCES alerts (alert_id)
);

CREATE INDEX idx_accounts_customer_id ON accounts (customer_id);
CREATE INDEX idx_transactions_account_id ON transactions (account_id);
CREATE INDEX idx_transactions_timestamp ON transactions (transaction_timestamp);
CREATE INDEX idx_alerts_customer_id ON alerts (customer_id);
CREATE INDEX idx_alerts_risk_score ON alerts (risk_score DESC);
